# Generated by Django 5.2.4 on 2025-07-08 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
