# Generated by Django 5.2.4 on 2025-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0002_submission_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="personal_details",
            field=models.TextField(default="No details provided"),
        ),
    ]
